### ISSUE TITLE
Automate setup and teardown of Redshift

### ISSUE THREAD

**Issue by rufuspollock** [cybergreen-net/aggregator#19]
Options for how we do this:
- terraform
- boto

Want to be able to call this from python code ... 
- [x] Research options
- [x] Implement given option!

**Comment by rgrp** [comment]
@zelima please do a bit of research on what these two options look like.

**Comment by zelima** [comment]
- Setting up a new cluster as well as teardown are pretty straightforward for both of them - just a few lines of code. 
- They both are well documented. But I can find more details, like default values or constraints for almost all arguments, in boto documentation.
- For sensitive variables terraform uses separate file `variables.tf`, while for boto3 we can use same .env file that will be used later by aggregator  scripts. 
- We since boto is python library we can include it in requirements.txt and no additional installation is required unlike terraform.

**Comment by zelima** [comment]
As application development stages are divided in two parts - `dev` and `prod`, besides creating new cluster, there's need of creating second database. Neither of them can give us an option to do that, as said in  [Boto3 docs](boto3.readthedocs.io/en/latest/reference/services/redshift.html#Redshift.Client.create_cluster)

> To create additional databases after the cluster is created, connect to the cluster with a SQL client and use SQL commands to create a database. For more information, go to Create a Database in the Amazon Redshift Database Developer Guide.

Considering that, we'll have to use python code to create second db in any case.
So rather than splitting code in to two different scripts, I would recommend to stick with one python script and Use Boto3

**Comment by rgrp** [comment]
@zelima great so we will use boto.

**Comment by rgrp** [comment]
@zelima or use ansible - i suggest we hold off here until we resolve https://github.com/cybergreen-net/infrastructure/issues/7

**Comment by rgrp** [comment]
@zelima ok, let's spend 2h or so doing this - should be very quick and we can use this no matter where we go on infrastructure.

**Comment by zelima** [comment]
Moving to backlog for now

**Comment by zelima** [comment]
DUPLICATE this one has moved into infrastructure repo. 
See https://github.com/cybergreen-net/infrastructure/issues/12 for further discussions
